window.gameData = {
  "tilesets": {
    "overworld": {
      "image": "assets/tiles/overworld.png",
      "tileWidth": 32,
      "tileHeight": 32,
      "columns": 8,
      "imageObj": {}
    },
    "interior": {
      "image": "assets/tiles/interior.png",
      "tileWidth": 32,
      "tileHeight": 32,
      "columns": 8,
      "imageObj": {}
    }
  },
  "decorDefs": {
    "tree_big": {
      "name": "Big Tree",
      "tilesetId": "overworld",
      "tileIndex": 16,
      "width": 32,
      "height": 48,
      "offsetY": 16,
      "blocks": true
    },
    "bush": {
      "name": "Bush",
      "tilesetId": "overworld",
      "tileIndex": 17,
      "width": 32,
      "height": 32,
      "offsetY": 0,
      "blocks": false
    },
    "bar_table": {
      "name": "Bar Table",
      "tilesetId": "interior",
      "tileIndex": 8,
      "width": 32,
      "height": 32,
      "offsetY": 0,
      "blocks": true
    },
    "bar_drink": {
      "name": "Drink",
      "tilesetId": "interior",
      "tileIndex": 9,
      "width": 16,
      "height": 16,
      "offsetY": 16,
      "blocks": false
    }
  },
  "items": {
    "fists": {
      "name": "Fists",
      "type": "weapon",
      "power": 3,
      "description": "Your bare hands. Better than nothing."
    },
    "clothes": {
      "name": "Clothes",
      "type": "armor",
      "defense": 0,
      "description": "Regular clothes. Not very protective."
    },
    "stick": {
      "name": "Wooden Stick",
      "type": "weapon",
      "power": 6,
      "description": "A simple stick that hits harder than your fists."
    },
    "kid_scarf": {
      "name": "Kid's Scarf",
      "type": "armor",
      "defense": 1,
      "description": "A cozy scarf from the forest kid. Sometimes softens blows."
    },
    "snack": {
      "name": "SNACK",
      "type": "consumable",
      "battleUse": "heal",
      "healAmount": 5,
      "description": "A small snack that heals 5 HP in battle."
    },
    "lucky_charm": {
      "name": "Lucky Charm",
      "type": "quest",
      "description": "A small charm. It probably belongs to someone."
    },
    "dummy_bandage": {
      "name": "Dummy Bandage",
      "type": "consumable",
      "battleUse": "heal",
      "healAmount": 7,
      "description": "A dusty bandage from the training dummy. Heals 7 HP."
    },
    "dummy_gloves": {
      "name": "Dummy Gloves",
      "type": "weapon",
      "power": 8,
      "description": "Heavy gloves from the training dummy. Your punches feel heavier."
    },
    "river_herb": {
      "name": "River Herb",
      "type": "quest",
      "description": "A fragrant herb from the Old Bridge. An herbalist might want this."
    },
    "stone_chunk": {
      "name": "Cliff Stone",
      "type": "quest",
      "description": "A solid chunk of stone from the cliff edge."
    },
    "bridge_mail": {
      "name": "Bridge Mail",
      "type": "armor",
      "defense": 2,
      "description": "Light armor reinforced with cliff stone."
    },
    "river_blade": {
      "name": "River Blade",
      "type": "weapon",
      "power": 10,
      "description": "A blade tempered by the river's current."
    },
    "ghost_cloak": {
      "name": "Ghost Cloak",
      "type": "armor",
      "defense": 3,
      "description": "A faded cloak from the shrine spirit. It feels strangely protective."
    },
    "moon_charm": {
      "name": "Moon Stone",
      "type": "armor",
      "defense": 4,
      "description": "A hidden moon stone from the shrine puzzle. It hums softly."
    },
    "moon_blade": {
      "name": "Moonlit Blade",
      "type": "weapon",
      "power": 14,
      "weaponDefBonus": 2,
      "description": "Your River Blade fused with the Moon Stone.\nHits harder and feels strangely protective."
    },
    "bar_ale": {
      "name": "Town Ale",
      "type": "consumable",
      "battleUse": "heal",
      "healAmount": 6,
      "description": "A mug of strong ale from the town bar. Restores 6 HP."
    },
    "bar_meal": {
      "name": "Bar Stew",
      "type": "consumable",
      "battleUse": "heal",
      "healAmount": 10,
      "description": "A hearty stew served with bread. Restores 10 HP."
    }
  },
  "rooms": {
    "field": {
      "id": "field",
      "name": "Grassy Path",
      "width": 1200,
      "height": 800,
      "spawnX": 300,
      "spawnY": 700,
      "tileLayer": {
        "tilesetId": "overworld",
        "tileWidth": 32,
        "tileHeight": 32,
        "gridWidth": 50,
        "gridHeight": 28,
        "tiles": [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          8,
          8,
          8,
          8,
          8,
          8,
          8,
          8,
          8,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          8,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          8,
          8,
          8,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          2,
          1,
          1,
          1,
          1,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          2,
          1,
          1,
          1,
          1,
          null,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          18,
          18,
          18,
          18,
          18,
          18,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          3,
          3,
          3,
          3,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          3,
          3,
          1,
          1,
          1,
          1,
          1,
          1,
          18,
          18,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          2,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          3,
          1,
          1,
          1,
          1,
          18,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          3,
          3,
          3,
          1,
          1,
          1,
          1,
          3,
          3,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          18,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          3,
          3,
          1,
          3,
          3,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          3,
          3,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          1
        ]
      },
      "decor": [
        {
          "id": "tree_big_0",
          "decorId": "tree_big",
          "x": 861.1295681063123,
          "y": 614.9253731343284
        },
        {
          "id": "bush_1",
          "decorId": "bush",
          "x": 608.7765221630347,
          "y": 356.5736997600768
        },
        {
          "id": "bush_2",
          "decorId": "bush",
          "x": 696.5424742672815,
          "y": 382.47011370913265
        },
        {
          "id": "bush_3",
          "decorId": "bush",
          "x": 646.6754560262322,
          "y": 382.47011370913265
        }
      ],
      "walls": [
        {
          "x": 0,
          "y": 0,
          "width": 500,
          "height": 60
        },
        {
          "x": 700,
          "y": 0,
          "width": 500,
          "height": 60
        },
        {
          "x": 0,
          "y": 740,
          "width": 1200,
          "height": 60
        },
        {
          "x": 0,
          "y": 60,
          "width": 60,
          "height": 680
        },
        {
          "x": 1140,
          "y": 60,
          "width": 60,
          "height": 680
        }
      ],
      "doors": [
        {
          "x": 540,
          "y": 0,
          "width": 120,
          "height": 40,
          "targetRoom": "forest",
          "targetX": 800,
          "targetY": 700,
          "message": "You walk into a quiet forest corridor."
        }
      ],
      "npcs": [
        {
          "id": "dummy",
          "x": 320,
          "y": 520,
          "width": 24,
          "height": 32,
          "hasBattle": true,
          "label": "Dummy",
          "dialogAfterBattle": "Dummy: \"Okay, okay, you win.\""
        },
        {
          "id": "lost_charm",
          "x": 900,
          "y": 300,
          "width": 16,
          "height": 16,
          "hasBattle": false,
          "label": "Shiny",
          "active": false
        }
      ]
    },
    "forest": {
      "id": "forest",
      "name": "Forest Corridor",
      "width": 1600,
      "height": 800,
      "tileLayer": {
        "tilesetId": "overworld",
        "tileWidth": 32,
        "tileHeight": 32,
        "gridWidth": 50,
        "gridHeight": 28,
        "tiles": []
      },
      "decor": [
        {
          "id": "tree_big_0",
          "decorId": "tree_big",
          "x": 220.59800664451825,
          "y": 620.8955223880597
        },
        {
          "id": "tree_big_1",
          "decorId": "tree_big",
          "x": 645.8471760797341,
          "y": 210.9452736318408
        },
        {
          "id": "tree_big_2",
          "decorId": "tree_big",
          "x": 1249.1694352159468,
          "y": 549.2537313432836
        },
        {
          "id": "tree_big_3",
          "decorId": "tree_big",
          "x": 1366.112956810631,
          "y": 216.91542288557216
        }
      ],
      "walls": [
        {
          "x": 0,
          "y": 0,
          "width": 1600,
          "height": 60
        },
        {
          "x": 0,
          "y": 740,
          "width": 700,
          "height": 60
        },
        {
          "x": 900,
          "y": 740,
          "width": 700,
          "height": 60
        },
        {
          "x": 0,
          "y": 60,
          "width": 60,
          "height": 680
        },
        {
          "x": 1540,
          "y": 60,
          "width": 60,
          "height": 260
        },
        {
          "x": 1540,
          "y": 440,
          "width": 60,
          "height": 300
        },
        {
          "x": 210,
          "y": 227,
          "width": 151,
          "height": 111
        },
        {
          "x": 890,
          "y": 336,
          "width": 154,
          "height": 96
        },
        {
          "x": 1106,
          "y": 181,
          "width": 149,
          "height": 88
        }
      ],
      "doors": [
        {
          "x": 740,
          "y": 760,
          "width": 120,
          "height": 40,
          "targetRoom": "field",
          "targetX": 600,
          "targetY": 120,
          "message": "You head back toward the grassy path."
        },
        {
          "x": 1540,
          "y": 320,
          "width": 60,
          "height": 120,
          "targetRoom": "cliffs",
          "targetX": 120,
          "targetY": 360,
          "message": "Cold air flows from the cliffside."
        }
      ],
      "npcs": [
        {
          "id": "kid",
          "x": 600,
          "y": 500,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Kid"
        },
        {
          "id": "training_dummy",
          "x": 450,
          "y": 520,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Trainer"
        },
        {
          "id": "chest",
          "x": 900,
          "y": 600,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Chest",
          "givesItemId": "snack",
          "givesItemQty": 1,
          "opened": false
        }
      ]
    },
    "cliffs": {
      "id": "cliffs",
      "name": "Cliff Edge",
      "width": 1200,
      "height": 900,
      "tileLayer": {
        "tilesetId": "overworld",
        "tileWidth": 32,
        "tileHeight": 32,
        "gridWidth": 50,
        "gridHeight": 28,
        "tiles": []
      },
      "decor": [],
      "walls": [
        {
          "x": 0,
          "y": 0,
          "width": 1200,
          "height": 60
        },
        {
          "x": 0,
          "y": 840,
          "width": 1200,
          "height": 60
        },
        {
          "x": 1.9933554817275763,
          "y": 203.28358208955225,
          "width": 60,
          "height": 320
        },
        {
          "x": 1138.0066445182724,
          "y": 225.67164179104486,
          "width": 60,
          "height": 320
        },
        {
          "x": 4.006644518272424,
          "y": 514.7611940298508,
          "width": 1190,
          "height": 331
        }
      ],
      "doors": [
        {
          "x": -1.9933554817275727,
          "y": 64.32835820895525,
          "width": 60,
          "height": 140,
          "targetRoom": "forest",
          "targetX": 1480,
          "targetY": 360,
          "message": "You squeeze back into the forest corridor."
        },
        {
          "x": 1138.0066445182724,
          "y": 64.32835820895517,
          "width": 60,
          "height": 160,
          "targetRoom": "river",
          "targetX": 80,
          "targetY": 420,
          "message": "You follow a narrow path down to a riverbank."
        }
      ],
      "npcs": [
        {
          "id": "sign",
          "x": 900,
          "y": 260,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Sign",
          "dialog": "Sign: \"Do NOT jump.\nAnd if you reach the shrine, remember:\nWest, East, then Middle.\""
        },
        {
          "id": "stone_chunk",
          "x": 550,
          "y": 280,
          "width": 16,
          "height": 16,
          "hasBattle": false,
          "label": "Stone",
          "active": false
        }
      ]
    },
    "river": {
      "id": "river",
      "name": "Riverbank",
      "width": 1600,
      "height": 900,
      "tileLayer": {
        "tilesetId": "overworld",
        "tileWidth": 32,
        "tileHeight": 32,
        "gridWidth": 50,
        "gridHeight": 28,
        "tiles": []
      },
      "decor": [],
      "walls": [
        {
          "x": 0,
          "y": 0,
          "width": 1600,
          "height": 60
        },
        {
          "x": 0,
          "y": 840,
          "width": 740,
          "height": 60
        },
        {
          "x": 860,
          "y": 840,
          "width": 740,
          "height": 60
        },
        {
          "x": 0,
          "y": 60,
          "width": 60,
          "height": 320
        },
        {
          "x": 0,
          "y": 540,
          "width": 60,
          "height": 300
        },
        {
          "x": 1540,
          "y": 60,
          "width": 60,
          "height": 780
        },
        {
          "x": 1026.0265780730897,
          "y": 42.38805970149258,
          "width": 545,
          "height": 813
        }
      ],
      "doors": [
        {
          "x": 0,
          "y": 380,
          "width": 60,
          "height": 160,
          "targetRoom": "cliffs",
          "targetX": 1100,
          "targetY": 420,
          "message": "You climb back up toward the cliffs."
        },
        {
          "x": 740,
          "y": 860,
          "width": 120,
          "height": 40,
          "targetRoom": "bridge",
          "targetX": 700,
          "targetY": 140,
          "message": "You follow the river down to an old bridge."
        }
      ],
      "npcs": [
        {
          "id": "herbalist",
          "x": 350,
          "y": 520,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Herbalist"
        },
        {
          "id": "river_guard",
          "x": 950,
          "y": 520,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Guard"
        }
      ]
    },
    "bridge": {
      "id": "bridge",
      "name": "Old Bridge",
      "width": 1400,
      "height": 700,
      "tileLayer": {
        "tilesetId": "overworld",
        "tileWidth": 32,
        "tileHeight": 32,
        "gridWidth": 50,
        "gridHeight": 28,
        "tiles": []
      },
      "decor": [],
      "walls": [
        {
          "x": 248.83720930232556,
          "y": 1.7412935323383039,
          "width": 600,
          "height": 60
        },
        {
          "x": 760,
          "y": 0,
          "width": 640,
          "height": 60
        },
        {
          "x": 0,
          "y": 640,
          "width": 1400,
          "height": 60
        },
        {
          "x": 0,
          "y": 60,
          "width": 60,
          "height": 580
        },
        {
          "x": 1340,
          "y": 60,
          "width": 60,
          "height": 220
        },
        {
          "x": 1340,
          "y": 400,
          "width": 60,
          "height": 240
        },
        {
          "x": 0,
          "y": 0,
          "width": 81,
          "height": 66
        },
        {
          "x": 1051.9245066077633,
          "y": 45.25697213804432,
          "width": 1037,
          "height": 226
        },
        {
          "x": 467,
          "y": 407,
          "width": 916,
          "height": 244
        }
      ],
      "doors": [
        {
          "x": 86.04651162790697,
          "y": 8.70646766169154,
          "width": 160,
          "height": 40,
          "targetRoom": "river",
          "targetX": 800,
          "targetY": 760,
          "message": "You head back toward the riverbank."
        },
        {
          "x": 1340,
          "y": 280,
          "width": 60,
          "height": 120,
          "targetRoom": "shrine",
          "targetX": 120,
          "targetY": 360,
          "message": "An old path leads to a ruined shrine."
        }
      ],
      "npcs": [
        {
          "id": "builder",
          "x": 400,
          "y": 500,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Builder"
        },
        {
          "id": "river_herb",
          "x": 700,
          "y": 340,
          "width": 16,
          "height": 16,
          "hasBattle": false,
          "label": "Herb",
          "active": false
        }
      ]
    },
    "shrine": {
      "id": "shrine",
      "name": "Ruined Shrine",
      "width": 1200,
      "height": 800,
      "tileLayer": {
        "tilesetId": "overworld",
        "tileWidth": 32,
        "tileHeight": 32,
        "gridWidth": 50,
        "gridHeight": 28,
        "tiles": []
      },
      "decor": [],
      "walls": [
        {
          "x": 0,
          "y": 0,
          "width": 1200,
          "height": 60
        },
        {
          "x": 0,
          "y": 740,
          "width": 540,
          "height": 60
        },
        {
          "x": 660,
          "y": 740,
          "width": 540,
          "height": 60
        },
        {
          "x": 0,
          "y": 60,
          "width": 60,
          "height": 260
        },
        {
          "x": 0,
          "y": 440,
          "width": 60,
          "height": 300
        },
        {
          "x": 1140,
          "y": 60,
          "width": 60,
          "height": 680
        },
        {
          "x": 300,
          "y": 260,
          "width": 600,
          "height": 40
        },
        {
          "x": 300,
          "y": 500,
          "width": 600,
          "height": 40
        }
      ],
      "doors": [
        {
          "x": 0,
          "y": 320,
          "width": 60,
          "height": 120,
          "targetRoom": "bridge",
          "targetX": 1280,
          "targetY": 320,
          "message": "You walk back toward the old bridge."
        },
        {
          "x": 540,
          "y": 760,
          "width": 120,
          "height": 40,
          "targetRoom": "trial",
          "targetX": 600,
          "targetY": 120,
          "message": "The floor opens into a long stone hall.",
          "requiresBossUnlock": true
        }
      ],
      "npcs": [
        {
          "id": "ghost",
          "x": 600,
          "y": 400,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Spirit"
        },
        {
          "id": "stoneA",
          "x": 360,
          "y": 560,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Stone"
        },
        {
          "id": "stoneB",
          "x": 600,
          "y": 560,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Stone"
        },
        {
          "id": "stoneC",
          "x": 840,
          "y": 560,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Stone"
        },
        {
          "id": "shrine_chest",
          "x": 580,
          "y": 320,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Chest",
          "givesItemId": "moon_charm",
          "givesItemQty": 1,
          "opened": false,
          "active": false
        },
        {
          "id": "statue",
          "x": 600,
          "y": 220,
          "width": 24,
          "height": 40,
          "hasBattle": false,
          "label": "Statue"
        }
      ]
    },
    "trial": {
      "id": "trial",
      "name": "Trial Hall",
      "width": 1200,
      "height": 800,
      "tileLayer": {
        "tilesetId": "overworld",
        "tileWidth": 32,
        "tileHeight": 32,
        "gridWidth": 50,
        "gridHeight": 28,
        "tiles": []
      },
      "decor": [],
      "walls": [
        {
          "x": 0,
          "y": 0,
          "width": 540,
          "height": 60
        },
        {
          "x": 660,
          "y": 0,
          "width": 540,
          "height": 60
        },
        {
          "x": 0,
          "y": 740,
          "width": 540,
          "height": 60
        },
        {
          "x": 660,
          "y": 740,
          "width": 540,
          "height": 60
        },
        {
          "x": 0,
          "y": 60,
          "width": 60,
          "height": 680
        },
        {
          "x": 1140,
          "y": 60,
          "width": 60,
          "height": 680
        },
        {
          "x": 260,
          "y": 260,
          "width": 60,
          "height": 260
        },
        {
          "x": 880,
          "y": 260,
          "width": 60,
          "height": 260
        }
      ],
      "doors": [
        {
          "x": 540,
          "y": 0,
          "width": 120,
          "height": 40,
          "targetRoom": "shrine",
          "targetX": 600,
          "targetY": 700,
          "message": "You climb back into the shrine."
        },
        {
          "x": 540,
          "y": 760,
          "width": 120,
          "height": 40,
          "targetRoom": "town",
          "targetX": 700,
          "targetY": 120,
          "message": "A door at the end of the hall stands open to the town above.",
          "requiresBossDefeated": true
        }
      ],
      "npcs": [
        {
          "id": "boss",
          "x": 600,
          "y": 520,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Judge"
        }
      ]
    },
    "town": {
      "id": "town",
      "name": "Clifftop Town",
      "width": 1400,
      "height": 900,
      "tileLayer": {
        "tilesetId": "overworld",
        "tileWidth": 32,
        "tileHeight": 32,
        "gridWidth": 50,
        "gridHeight": 28,
        "tiles": []
      },
      "decor": [],
      "walls": [
        {
          "x": 0,
          "y": 0,
          "width": 600,
          "height": 60
        },
        {
          "x": 800,
          "y": 0,
          "width": 600,
          "height": 60
        },
        {
          "x": 0,
          "y": 840,
          "width": 1400,
          "height": 60
        },
        {
          "x": 0,
          "y": 60,
          "width": 60,
          "height": 780
        },
        {
          "x": 1340,
          "y": 60,
          "width": 60,
          "height": 780
        },
        {
          "x": 200,
          "y": 200,
          "width": 200,
          "height": 40
        },
        {
          "x": 200,
          "y": 240,
          "width": 40,
          "height": 260
        },
        {
          "x": 400,
          "y": 400,
          "width": 300,
          "height": 40
        },
        {
          "x": 858,
          "y": 289,
          "width": 172,
          "height": 90
        },
        {
          "x": 974,
          "y": 354,
          "width": 63,
          "height": 168
        }
      ],
      "doors": [
        {
          "x": 600,
          "y": 0,
          "width": 200,
          "height": 40,
          "targetRoom": "trial",
          "targetX": 600,
          "targetY": 700,
          "message": "You descend back into the trial hall below."
        },
        {
          "x": 904.6511627906976,
          "y": 378.955223880597,
          "width": 80,
          "height": 120,
          "targetRoom": "bar",
          "targetX": 220,
          "targetY": 520,
          "message": "You step into the Lantern Bar."
        }
      ],
      "npcs": [
        {
          "id": "town_gazer",
          "x": 320,
          "y": 520,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Resident",
          "dialog": "Resident: \"Most folks only reach this town in stories.\nYou walked here for real.\""
        }
      ]
    },
    "bar": {
      "id": "bar",
      "name": "Lantern Bar",
      "width": 1200,
      "height": 800,
      "tileLayer": {
        "tilesetId": "overworld",
        "tileWidth": 32,
        "tileHeight": 32,
        "gridWidth": 50,
        "gridHeight": 28,
        "tiles": []
      },
      "decor": [],
      "walls": [
        {
          "x": 0,
          "y": 0,
          "width": 500,
          "height": 60
        },
        {
          "x": 700,
          "y": 0,
          "width": 500,
          "height": 60
        },
        {
          "x": 0,
          "y": 740,
          "width": 1200,
          "height": 60
        },
        {
          "x": 0,
          "y": 60,
          "width": 60,
          "height": 680
        },
        {
          "x": 1140,
          "y": 60,
          "width": 60,
          "height": 680
        },
        {
          "x": 219,
          "y": 245,
          "width": 116,
          "height": 16
        }
      ],
      "doors": [
        {
          "x": 500,
          "y": 0,
          "width": 200,
          "height": 40,
          "targetRoom": "town",
          "targetX": 1040,
          "targetY": 520,
          "message": "You step back out into the town air."
        }
      ],
      "npcs": [
        {
          "id": "bartender",
          "x": 260,
          "y": 220,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Bartender"
        },
        {
          "id": "wizardA",
          "x": 700,
          "y": 330,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Wizard"
        },
        {
          "id": "wizardB",
          "x": 840,
          "y": 330,
          "width": 24,
          "height": 32,
          "hasBattle": false,
          "label": "Wizard"
        }
      ]
    }
  },
  "enemies": {
    "dummy": {
      "name": "Dummy",
      "maxHp": 30,
      "lines": [
        "Dummy: \"Not bad for a first hit!\"",
        "Dummy: \"You call that dodging?\"",
        "Dummy: \"I've seen tougher attacks from a pillow.\"",
        "Dummy: \"Okay, now I'm getting serious!\""
      ],
      "patterns": [
        0,
        1,
        2
      ]
    },
    "training_dummy": {
      "name": "Training Dummy",
      "maxHp": 20,
      "lines": [
        "Training Dummy: \"Focus on your timing!\"",
        "Training Dummy: \"Watch the patterns.\""
      ],
      "patterns": [
        0
      ]
    },
    "river_beast": {
      "name": "River Beast",
      "maxHp": 40,
      "lines": [
        "The river beast churns the water.",
        "River Beast: \"GLUB...\""
      ],
      "patterns": [
        1,
        2
      ]
    },
    "shrine_spirit": {
      "name": "Shrine Spirit",
      "maxHp": 50,
      "lines": [
        "Spirit: \"You carry many promises.\"",
        "Spirit: \"Show me your resolve.\""
      ],
      "patterns": [
        0,
        2
      ]
    },
    "trial_boss": {
      "name": "Judge of Steps",
      "maxHp": 80,
      "lines": [
        "Judge: \"Every step you took brought you here.\"",
        "Judge: \"Strength is just choices repeated.\"",
        "Judge: \"Do not flinch now.\""
      ],
      "patterns": [
        3,
        4,
        5
      ]
    },
    "wizard_duo": {
      "name": "Feuding Wizards",
      "maxHp": 80,
      "isDuo": true,
      "duoNames": [
        "Azure",
        "Crimson"
      ],
      "duoMaxHp": [
        40,
        40
      ],
      "lines": [
        "Azure: \"I am still certain YOU broke it.\"",
        "Crimson: \"If you'd stop yelling, maybe we'd see clearly.\"",
        "The argument somehow gets louder."
      ],
      "patterns": [
        1,
        3,
        5
      ]
    }
  }
};
